### PR TITLE
Remove Three.js

### PR DESCRIPTION
**Pull request by noahk004**
## Changes
Removed three and react-three.

### CODE REVIEW

**Comment by IanWearsHat** [comment]
Could you also: 
- Remove `tunnel-rat`, `types/three`, `react-three/drei`, and `react-three/fiber` dependencies
- Delete the `site\src\components` and `site\src\helpers` directories
- Remove components that use them in `site\src\app\(main)\layout.tsx`, `site\src\app\(main)\(home)\sections\Landing\Landing.tsx`

**Comment by waalbert** [comment]
Yes, as Ian and I discussed before early on, we believe that anything that depends on Three.js will not be needed. Three.js will just add unnecessary complexity and more overhead since we don't need it for IH 25.

**Comment by waalbert** [comment]
From brief testing, these changes seem to reduce resources usage on my end by a little bit. I will do more testing.

**Review by taesungh — APPROVED** [review]
Thanks for cleaning this up.

**Review by IanWearsHat — APPROVED** [review]
Thanks Noah!

**Review by waalbert — APPROVED** [review]
Thanks for the cleanup Noah!

**Pull request merged**
